name: salictestes
on: push
jobs:
  build:
    runs-on: dev2
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

  deploy-dev:
     runs-on: dev2
     environment: 
      name: desenvolvimento
      url: 'centraldevops.com'
     needs: build
     steps:
      - name: executando script para levantar aplicação Desenvolvimento
        run: echo Hello, world!

