name: salicmain
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: dev
    steps:
      - name: Checkout para clonar codigo fonte
        uses: actions/checkout@v2



