name: salictestesv1
on: push
jobs:
  build:
    runs-on: dev3
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

  deploy-dev:
     runs-on: dev3
     environment: 
      name: desenvolvimento
      url: 'centraldevops.com'
     needs: build
     steps:
      - name: Dando Permissão script install e execultando ... 
        run: chmod 775 /opt/actions-runner/repositorio/salic-api/salic-api/install.sh
        
      - name: Execultando script... 
        run: /opt/actions-runner/repositorio/salic-api/salic-api/install.sh 
              
