name: salictestes
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: dev2
    steps:
      - name: Checkout para clonar codigo fonte
        uses: actions/checkout@v2

  deploy-dev:
     runs-on: dev2
     environment: 
      name: desenvolvimento
      url: 'centraldevops.com'
     needs: build
     steps:
      - name: executando script para levantar aplicação Desenvolvimento
        run: echo Hello, world!

